"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import PasswordField from "./password-field";

export default function AuthForm({ mode = "login", token = "", initialSessionType = "central", needsSetup = false }) {
  const router = useRouter();
  const [message, setMessage] = useState(""), [busy, setBusy] = useState(false), [sessionType, setSessionType] = useState(initialSessionType);
  async function submit(event) { event.preventDefault(); setMessage(""); setBusy(true); try { const form = new FormData(event.currentTarget), body = Object.fromEntries(form); if (token) body.token = token; if (mode === "login") body.sessionType = sessionType; const response = await fetch(`/api/auth/${mode}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }), result = await response.json(); if (!response.ok) return setMessage(result.error); if (mode === "login" || mode === "reset-password") { if (result.warning) sessionStorage.setItem("krio-notice", result.warning); router.push("/"); router.refresh(); return; } setMessage(result.resetUrl ? `${result.message} ${location.origin}${result.resetUrl}` : result.message); } finally { setBusy(false); } }
  function connectToCentral(event) { event.preventDefault(); setMessage(""); try { const form = new FormData(event.currentTarget), url = new URL(String(form.get("centralUrl"))), host = url.hostname; if (!/^https?:$/.test(url.protocol) || !(host === "localhost" || host === "127.0.0.1" || host === "::1" || /^10\./.test(host) || /^192\.168\./.test(host) || /^172\.(1[6-9]|2\d|3[01])\./.test(host))) throw new Error(); url.pathname = "/login"; url.search = "?session=user"; location.assign(url); } catch { setMessage("Yerel ağdaki geçerli merkez adresini girin (ör. http://192.168.1.10:3000)."); } }
  const title = mode === "login" ? needsSetup ? "Merkez kurulumu" : "Tekrar hoş geldiniz" : mode === "forgot-password" ? "Parolanızı sıfırlayın" : "Yeni parolanızı oluşturun";
  const description = mode === "login" ? needsSetup ? "Lisansınızı etkinleştirin ve ilk admin hesabını oluşturun." : "Devam etmek için bilgilerinizi girin." : mode === "forgot-password" ? "Sıfırlama bağlantısını gönderebilmemiz için e-posta adresinizi girin." : "Hesabınız için en az 10 karakterli yeni bir parola belirleyin.";
  const createsPassword = mode === "reset-password" || mode === "login" && needsSetup;
  return <main className="auth-page"><section className="auth-copy"><KrioLogo /><div><span className="auth-eyebrow">İLETİŞİM, DAHA NET</span><h1>Müşterilerinizle tek bir yerden iletişim kurun.</h1><p>WhatsApp profillerinizi, konuşmalarınızı ve toplu gönderimlerinizi kolayca yönetin.</p></div><small>Krio Notifications · easyplus güvencesiyle</small></section><section className="auth-form"><div className="auth-inner"><div className="auth-mobile-brand"><KrioLogo /></div>{mode !== "login" && <a className="auth-back" href="/login">← Girişe dön</a>}<h2>{title}</h2><p>{description}</p>{mode === "login" && !needsSetup && <div className="auth-tabs"><button className={sessionType === "central" ? "active" : ""} onClick={() => setSessionType("central")} type="button">Merkez Oturum</button><button className={sessionType === "user" ? "active" : ""} onClick={() => setSessionType("user")} type="button">Kullanıcı Oturumu</button></div>}{mode === "login" && sessionType === "user" && initialSessionType !== "user" && !needsSetup ? <form onSubmit={connectToCentral}><label className="auth-field">Merkez adresi<input name="centralUrl" type="url" placeholder="http://192.168.1.10:3000" required autoFocus /></label><button className="auth-submit">Merkeze bağlan</button>{message && <p className="auth-notice" role="status">{message}</p>}</form> : <form onSubmit={submit}>{mode !== "reset-password" && <label className="auth-field">E-posta adresi<input name="email" type="email" autoComplete="email" required autoFocus /></label>}{mode !== "forgot-password" && <PasswordField className="auth-field" name="password" label="Parola" minLength="10" autoComplete={createsPassword ? "new-password" : "current-password"} required strength={createsPassword} autoFocus={mode === "reset-password"} />}{mode === "login" && needsSetup && <><PasswordField className="auth-field" name="passwordConfirmation" label="Parola tekrarı" minLength="10" autoComplete="new-password" required /><label className="auth-field">Lisans anahtarı<input name="licenceKey" maxLength="64" autoComplete="off" required /></label></>}{mode === "login" && !needsSetup && <a className="auth-forgot" href="/forgot-password">Parolamı unuttum</a>}<button className="auth-submit" disabled={busy}>{busy ? "Lütfen bekleyin…" : mode === "login" ? needsSetup ? "Merkezi kur" : "Giriş yap" : mode === "forgot-password" ? "Sıfırlama bağlantısı gönder" : "Parolayı kaydet"}</button>{message && <p className="auth-notice" role="status">{message}</p>}</form>}</div></section></main>;
}

function KrioLogo() { return <span className="krio-brand" aria-label="Krio Notify"><span className="krio-mark" aria-hidden="true"><i /><i /><i /><i /></span><span className="krio-wordmark"><b>KRIO</b><small>easyplus</small></span><span className="krio-product">Krio Notify</span></span>; }
