import { NextResponse } from "next/server";
import { authError, hashPassword, requireUser } from "../../../../lib/auth";
import { Session, User } from "../../../../lib/db";

const view = (user) => ({ id: user.id, email: user.email, role: user.role, profileIds: JSON.parse(user.profileIds || "[]") });
export async function GET(request) { try { await requireUser(request, { admin: true }); return NextResponse.json({ users: (await User.findAll({ order: [["email", "ASC"]] })).map(view) }); } catch (error) { const x = authError(error); return NextResponse.json({ error: x.message }, { status: x.status }); } }
export async function POST(request) { try { await requireUser(request, { admin: true }); const { email, password, role = "user", profileIds = [] } = await request.json(); if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email || "") || !["admin", "user"].includes(role) || !Array.isArray(profileIds)) throw new Error("Geçersiz kullanıcı bilgisi."); const user = await User.create({ email: email.trim().toLowerCase(), passwordHash: await hashPassword(password), role, profileIds: JSON.stringify(profileIds) }); return NextResponse.json({ user: view(user) }, { status: 201 }); } catch (error) { const x = authError(error); return NextResponse.json({ error: error.name === "SequelizeUniqueConstraintError" ? "Bu e-posta zaten kayıtlı." : x.message }, { status: x.status }); } }
export async function PATCH(request) { try { const actor = await requireUser(request, { admin: true }), { id, role, profileIds, password } = await request.json(), user = await User.findByPk(id); if (!user) throw Object.assign(new Error("Kullanıcı bulunamadı."), { status: 404 }); if (id === actor.id && role && role !== "admin") throw new Error("Kendi admin rolünüzü kaldıramazsınız."); const values = {}; if (role) { if (!["admin", "user"].includes(role)) throw new Error("Geçersiz rol."); values.role = role; } if (profileIds) { if (!Array.isArray(profileIds)) throw new Error("Geçersiz profil listesi."); values.profileIds = JSON.stringify(profileIds); } if (password) values.passwordHash = await hashPassword(password); await user.update(values); if (password) await Session.destroy({ where: { userId: id } }); return NextResponse.json({ user: view(user) }); } catch (error) { const x = authError(error); return NextResponse.json({ error: x.message }, { status: x.status }); } }
export async function DELETE(request) { try { const actor = await requireUser(request, { admin: true }), id = request.nextUrl.searchParams.get("id"); if (id === actor.id) throw new Error("Kendi hesabınızı silemezsiniz."); await Session.destroy({ where: { userId: id } }); const count = await User.destroy({ where: { id } }); if (!count) throw Object.assign(new Error("Kullanıcı bulunamadı."), { status: 404 }); return NextResponse.json({ ok: true }); } catch (error) { const x = authError(error); return NextResponse.json({ error: x.message }, { status: x.status }); } }
