export const state = {
  whatsAppAuth: { state: 'starting' },
  appSession: { loading: true },
  appUsers: [],
  chats: [],
  chatsLoaded: false,
  profiles: [],
  selected: null,
  messages: [],
  messageState: 'idle',
  messageError: '',
  draft: '',
  sending: false,
  loggingOut: false,
  selectionRequest: 0,
  searchQuery: '',
  sidebarScroll: 0,
  emojiOpen: false,
  typingChat: null,
  typingTimer: undefined,
  settingsOpen: false,
  bulkOpen: false,
  statusOpen: false,
  statusPosts: [],
  statusSubmitting: false,
  statusRefreshTimer: undefined,
  statusDraft: { profileId: '', kind: 'text', text: '', mode: 'now', scheduledLocal: '' },
  bulkTemplates: [],
  bulkRecipients: [],
  bulkProfile: '',
  bulkTemplate: 0,
  editingTemplate: 0,
  bulkMode: 'excel',
  bulkRows: [],
  bulkFileError: '',
  bulkReports: [],
  bulkReport: null,
  bulkRefreshTimer: undefined,
  bulkSection: 'send',
  replyTo: null,
  actionMessage: null,
  forwarding: null,
  forwardQuery: '',
  audioContext: undefined,
  remoteTyping: null,
  remoteTypingTimer: undefined,
  profileSwitching: false,
  eventSource: undefined,
  syncingProfiles: new Set(),
}
